# Generated by Django 3.2.5 on 2021-12-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(blank=True, max_length=100)),
                ('lisence_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bus_fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lisence_no', models.CharField(max_length=100)),
                ('start_point', models.CharField(max_length=50)),
                ('end_point', models.CharField(max_length=50)),
                ('fair', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='bus_route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lisence_no', models.CharField(max_length=100)),
                ('point_one', models.CharField(blank=True, max_length=50)),
                ('point_two', models.CharField(blank=True, max_length=50)),
                ('point_three', models.CharField(blank=True, max_length=50)),
                ('point_four', models.CharField(blank=True, max_length=50)),
                ('point_five', models.CharField(blank=True, max_length=50)),
                ('point_six', models.CharField(blank=True, max_length=50)),
                ('point_seven', models.CharField(blank=True, max_length=50)),
                ('point_eight', models.CharField(blank=True, max_length=50)),
                ('point_nine', models.CharField(blank=True, max_length=50)),
                ('point_ten', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
